# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12_LDbz-D4_l1iSWTymZqXo9vcnQURxgH
"""

# Function to get to know a person
def get_to_know_person():
    # Dictionary to store person's details
    person_details = {}

    # Asking basic questions
    person_details['name'] = input("What's your name? ")
    person_details['age'] = input("How old are you? ")
    person_details['hobby'] = input("What is your favorite hobby? ")
    person_details['favorite_food'] = input("What's your favorite food? ")
    person_details['dream_destination'] = input("Where would you love to travel? ")

    # Output a summary
    print("\nNice to meet you! Here's what I've learned about you:")
    for key, value in person_details.items():
        print(f"{key.capitalize()}: {value}")

# Run the function
get_to_know_person()