# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17EF502I8VhWjYODw3sEcj2TWuK50A2YQ
"""

! pip install streamlit